name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  home:
    path: packages/home
  pay:
    path: packages/pay
  login:
    path: packages/login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^7.2.0

flutter:
  uses-material-design: true
